name       : htop
version    : 3.1.1
release    : 16
source     :
    - https://github.com/htop-dev/htop/archive/refs/tags/3.1.1.tar.gz : b52280ad05a535ec632fbcd47e8e2c40a9376a9ddbd7caa00b38b9d6bb87ced6
homepage   : https://htop.dev
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
builddeps  :
    - lm_sensors-devel
rundeps    :
    - lm_sensors
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
