name       : htop
version    : 3.0.0
release    : 9
source     :
    - https://github.com/htop-dev/htop/archive/3.0.0.tar.gz : 1c0661f0ae5f4e2874da250b60cd515e4ac4c041583221adfe95f10e18d1a4e6
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
