name       : htop
version    : 2.0.2
release    : 6
source     :
    - http://hisham.hm/htop/releases/2.0.2/htop-2.0.2.tar.gz : 179be9dccb80cee0c5e1a1f58c8f72ce7b2328ede30fb71dcdf336539be2f487
license    : GPL-2.0
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
