name       : htop
version    : 3.1.2
release    : 17
source     :
    - https://github.com/htop-dev/htop/releases/download/3.1.2/htop-3.1.2.tar.xz : 884bce5b58cb113127860b9e368609019e92416a81550fdf0752052f3a64b388
homepage   : https://htop.dev
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
builddeps  :
    - lm_sensors-devel
rundeps    :
    - lm_sensors
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
