name       : htop
version    : 2.0.2
release    : 5
source     :
    - http://hisham.hm/htop/releases/2.0.2/htop-2.0.2.tar.gz : 179be9dccb80cee0c5e1a1f58c8f72ce7b2328ede30fb71dcdf336539be2f487
license    :
    - GPLv2
summary    : htop (interactive process viewer for Linux)
builddeps  :
    - ncurses-devel
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
