name       : htop
version    : 2.2.0
release    : 8
source     :
    - https://hisham.hm/htop/releases/2.2.0/htop-2.2.0.tar.gz : d9d6826f10ce3887950d709b53ee1d8c1849a70fa38e91d5896ad8cbc6ba3c57
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
