name       : htop
version    : 3.0.5
release    : 13
source     :
    - https://github.com/htop-dev/htop/archive/3.0.5.tar.gz : 4c2629bd50895bd24082ba2f81f8c972348aa2298cc6edc6a21a7fa18b73990c
homepage   : https://htop.dev
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
builddeps  :
    - lm_sensors-devel
rundeps    :
    - lm_sensors
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
