name        : htop
version     : 1.0.3
release     : 2
source      :
    - http://hisham.hm/htop/releases/1.0.3/htop-1.0.3.tar.gz : 055c57927f75847fdc222b5258b079a9542811a9dcf5421c615c7e17f55d1829
homepage    : http://htop.sourceforge.net/index.php
license     :
    - GPLv2
summary     : htop (interactive process viewer for Linux)
builddeps   :
    - ncurses-devel
description : |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
