name        : htop
version     : 2.0.0
release     : 3
source     :
    - http://hisham.hm/htop/releases/2.0.0/htop-2.0.0.tar.gz : d15ca2a0abd6d91d6d17fd685043929cfe7aa91199a9f4b3ebbb370a2c2424b5
license     :
    - GPLv2
summary     : htop (interactive process viewer for Linux)
builddeps   :
    - ncurses-devel
description : |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
