name        : htop
version     : 2.0.1
release     : 4
source     :
    - http://hisham.hm/htop/releases/2.0.1/htop-2.0.1.tar.gz : f410626dfaf6b70fdf73cd7bb33cae768869707028d847fed94a978e974f5666
license     :
    - GPLv2
summary     : htop (interactive process viewer for Linux)
builddeps   :
    - ncurses-devel
description : |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
