name       : htop
version    : 3.0.3
release    : 11
source     :
    - https://github.com/htop-dev/htop/archive/3.0.3.tar.gz : 725103929c925a7252b4dedeb29b3a1da86a2f74e96c50eb9ea6c8fec1942cd2
homepage   : https://htop.dev/
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
