name       : htop
version    : 3.0.4
release    : 12
source     :
    - https://github.com/htop-dev/htop/archive/3.0.4.tar.gz : d8a0536ce95e3d59f8e292e73ee037033a74a8cc118fd10d22048bd4aeb61324
homepage   : https://htop.dev/
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
