name       : htop
version    : 2.1.0
release    : 7
source     :
    - https://hisham.hm/htop/releases/2.1.0/htop-2.1.0.tar.gz : 3260be990d26e25b6b49fc9d96dbc935ad46e61083c0b7f6df413e513bf80748
license    : GPL-2.0
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

