name       : htop
version    : 3.2.0
release    : 19
source     :
    - https://github.com/htop-dev/htop/releases/download/3.2.0/htop-3.2.0.tar.xz : e0f645d4ac324f2c4c48aaa7a3a96d007b95516559550be0b56e423fc5b6d783
homepage   : https://htop.dev
license    : GPL-2.0-or-later
component  : system.utils
summary    : htop (interactive process viewer for Linux)
description: |
    htop is an interactive process viewer for Linux.
builddeps  :
    - lm_sensors-devel
rundeps    :
    - lm_sensors
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
